[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/logo/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/clinica/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/equipe/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"